PRESETS: dict[str, list[str]] = {
	'social': [
		'facebook.com',
		'www.facebook.com',
		'instagram.com',
		'www.instagram.com',
		'twitter.com',
		'www.twitter.com',
		'x.com',
		'www.x.com',
		'tiktok.com',
		'www.tiktok.com',
		'reddit.com',
		'www.reddit.com',
		'threads.net',
		'www.threads.net',
		'linkedin.com',
		'www.linkedin.com',
		'snapchat.com',
		'www.snapchat.com',
	],
	'video': [
		'youtube.com',
		'www.youtube.com',
		'netflix.com',
		'www.netflix.com',
		'twitch.tv',
		'www.twitch.tv',
		'disneyplus.com',
		'www.disneyplus.com',
		'hulu.com',
		'www.hulu.com',
		'primevideo.com',
		'www.primevideo.com',
	],
	'gaming': [
		'steampowered.com',
		'steamcommunity.com',
		'epicgames.com',
		'www.epicgames.com',
		'discord.com',
		'www.discord.com',
		'roblox.com',
		'www.roblox.com',
		'battlenet.com',
		'www.battlenet.com',
	],
	'shopping': [
		'amazon.com',
		'www.amazon.com',
		'ebay.com',
		'www.ebay.com',
		'etsy.com',
		'www.etsy.com',
		'aliexpress.com',
		'www.aliexpress.com',
	],
	'news': [
		'cnn.com',
		'www.cnn.com',
		'bbc.com',
		'www.bbc.com',
		'nytimes.com',
		'www.nytimes.com',
		'theguardian.com',
		'www.theguardian.com',
		'news.ycombinator.com',
	],
	'adult': [
		'pornhub.com',
		'www.pornhub.com',
		'xvideos.com',
		'www.xvideos.com',
		'xnxx.com',
		'www.xnxx.com',
		'onlyfans.com',
		'www.onlyfans.com',
	],
}

# The "all" preset combines everything
PRESETS['all'] = list(set(domain for domains in PRESETS.values() for domain in domains))
